openapi: 3.0.0
info:
  title: anticloud
  description: anticloud
  version: 0.0.1
servers:
  - url: "/api"
paths:
  /ls:
    $ref: "paths/ls.yml"
  /size:
    $ref: "paths/size.yml"
  /free:
    $ref: "paths/free.yml"
#  /store:
#    $ref: "paths/store.yml"